name: Funktionswunsch
description: Eine Verbesserung oder neue Funktion vorschlagen
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Ausgangssituation
      description: Welches Problem oder welcher Arbeitsablauf soll verbessert werden?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Gewünschte Lösung
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternativen / Ergänzungen
