from django.conf import settings
from django.db import migrations,models
import django.db.models.deletion
class Migration(migrations.Migration):
 dependencies=[('members','0005_memberbadge'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
 operations=[
  migrations.CreateModel(name='Todo',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=200,verbose_name='Titel')),('description',models.TextField(blank=True,verbose_name='Beschreibung')),('category',models.CharField(choices=[('team','Teamintern'),('family','Mit Kind / Eltern klären')],default='team',max_length=20,verbose_name='Kategorie')),('target_type',models.CharField(choices=[('single','Ein Mitglied'),('multiple','Mehrere Mitglieder'),('all','Alle Mitglieder')],default='single',max_length=20,verbose_name='Gilt für')),('deadline',models.DateField(verbose_name='Deadline')),('completed',models.BooleanField(default=False,verbose_name='Erledigt')),('completed_at',models.DateTimeField(blank=True,null=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('assigned_to',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='assigned_todos',to=settings.AUTH_USER_MODEL,verbose_name='Zuständig')),('completed_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='completed_todos',to=settings.AUTH_USER_MODEL)),('created_by',models.ForeignKey(null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='created_todos',to=settings.AUTH_USER_MODEL)),('members',models.ManyToManyField(blank=True,related_name='todos',to='members.member'))],options={'ordering':('completed','deadline','title')}),
  migrations.CreateModel(name='TodoMemberStatus',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('completed',models.BooleanField(default=False)),('completed_at',models.DateTimeField(blank=True,null=True)),('note',models.CharField(blank=True,max_length=300,verbose_name='Notiz')),('completed_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='completed_member_todos',to=settings.AUTH_USER_MODEL)),('member',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='todo_statuses',to='members.member')),('todo',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='member_statuses',to='todos.todo'))]),
  migrations.AddConstraint(model_name='todomemberstatus',constraint=models.UniqueConstraint(fields=('todo','member'),name='unique_todo_member_status'))]
