from django.conf import settings
from django.db import migrations,models
import django.db.models.deletion
def seed_bks(apps,schema_editor):
    ExternalLink=apps.get_model("core","ExternalLink")
    ExternalLink.objects.get_or_create(name="BKS-Cloud",defaults={"url":"https://cloud.bks-portal.rlp.de","icon":"☁","category":"Werkzeuge","visible":True,"favorite":True,"order":1})
class Migration(migrations.Migration):
    dependencies=[("core","0001_appsettings"),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[migrations.CreateModel(name="ExternalLink",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(max_length=100,verbose_name="Name")),("url",models.URLField(verbose_name="URL")),("icon",models.CharField(blank=True,default="↗",max_length=10,verbose_name="Icon")),("category",models.CharField(blank=True,default="Werkzeuge",max_length=80,verbose_name="Kategorie")),("visible",models.BooleanField(default=True,verbose_name="Sichtbar")),("favorite",models.BooleanField(default=False,verbose_name="Dashboard-Favorit")),("order",models.PositiveSmallIntegerField(default=10,verbose_name="Reihenfolge"))],options={"verbose_name":"Externer Link","verbose_name_plural":"Externe Links","ordering":("order","name")}),migrations.CreateModel(name="DashboardPreference",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("show_member_counts",models.BooleanField(default=True,verbose_name="Mitgliederzahlen")),("show_gender_chart",models.BooleanField(default=True,verbose_name="Geschlechterdiagramm")),("show_status_chart",models.BooleanField(default=True,verbose_name="Statusdiagramm")),("show_next_activities",models.BooleanField(default=True,verbose_name="Nächste Termine")),("show_birthdays",models.BooleanField(default=True,verbose_name="Geburtstage")),("show_waiting_list",models.BooleanField(default=True,verbose_name="Warteliste")),("show_attendance",models.BooleanField(default=True,verbose_name="Anwesenheit")),("show_quick_actions",models.BooleanField(default=True,verbose_name="Schnellaktionen")),("user",models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name="dashboard_preference",to=settings.AUTH_USER_MODEL))]),migrations.RunPython(seed_bks,migrations.RunPython.noop)]
